apiVersion: monitoring.coreos.com/v1alpha1
kind: AlertmanagerConfig
metadata:
  labels:
    alertmanagerConfig: baseline
    app.kubernetes.io/managed-by: o11y
  name: baseline
  namespace: monitoring
spec:
  inhibitRules:
  - equal:
    - alertname
    - cluster
    - namespace
    sourceMatch:
    - matchType: =
      name: severity
      value: critical
    targetMatch:
    - matchType: =
      name: severity
      value: warning
  - equal:
    - cluster
    - node
    sourceMatch:
    - matchType: =
      name: alertname
      value: KubeNodeNotReady
    targetMatch:
    - matchType: =
      name: severity
      value: warning
  receivers:
  - name: "null"
  - name: pager
  - name: critical-chat
    slackConfigs:
    - apiURL:
        key: url
        name: alertmanager-slack-webhook
      color: danger
      sendResolved: true
      text: |
        {{ range .Alerts -}}
        *Severity:* `{{ .Labels.severity }}`
        *Alert:* {{ .Labels.alertname }}{{ if .Labels.namespace }} | ns: `{{ .Labels.namespace }}`{{ end }}
        {{ if .Annotations.summary }}*Summary:* {{ .Annotations.summary }}
        {{ end -}}
        {{ if .Annotations.description }}*Description:* {{ .Annotations.description }}
        {{ end -}}
        {{ if .Annotations.runbook_url }}*Runbook:* {{ .Annotations.runbook_url }}
        {{ end -}}
        ---
        {{ end }}
      title: '[CRITICAL] {{ .GroupLabels.alertname }}{{ if .GroupLabels.namespace }} ({{ .GroupLabels.namespace }}){{ end }}'
  - name: warning-chat
    slackConfigs:
    - apiURL:
        key: url
        name: alertmanager-slack-webhook
      color: warning
      sendResolved: true
      text: |
        {{ range .Alerts -}}
        *Severity:* `{{ .Labels.severity }}`
        *Alert:* {{ .Labels.alertname }}{{ if .Labels.namespace }} | ns: `{{ .Labels.namespace }}`{{ end }}
        {{ if .Annotations.summary }}*Summary:* {{ .Annotations.summary }}
        {{ end -}}
        {{ if .Annotations.description }}*Description:* {{ .Annotations.description }}
        {{ end -}}
        {{ if .Annotations.runbook_url }}*Runbook:* {{ .Annotations.runbook_url }}
        {{ end -}}
        ---
        {{ end }}
      title: '[WARNING] {{ .GroupLabels.alertname }}{{ if .GroupLabels.namespace }} ({{ .GroupLabels.namespace }}){{ end }}'
  route:
    groupBy:
    - alertname
    - cluster
    - namespace
    groupInterval: 5m
    groupWait: 30s
    receiver: "null"
    repeatInterval: 4h
    routes:
    - continue: true
      matchers:
      - matchType: =
        name: severity
        value: critical
      receiver: pager
      repeatInterval: 1h
    - matchers:
      - matchType: =
        name: severity
        value: critical
      receiver: critical-chat
    - matchers:
      - matchType: =
        name: severity
        value: warning
      receiver: warning-chat
      repeatInterval: 12h
